services:
  - type: static
    name: ksainv-frontend
    env: static
    root: client           # waar package.json & build output zitten
    buildCommand: npm run build
    publishPath: dist      # Vite’s output-map binnen client/
    routes:
      - type: rewrite
        src: /(.*)
        dest: /index.html
